name = "update-kv-images"
type = "javascript"

account_id = "7e5099001e49da7bd8e6f6eeb7e602e8"
workers_dev = true
# route = ""
# zone_id = ""

compatibility_date = "2022-02-15"
compatibility_flags = []

[[migrations]]
tag = "v1"
new_classes = ["Counter"]

[build]
command = "npm run build"

[build.upload]
format = "modules"
dir = "dist"
main = "./index.mjs"

[miniflare]
kv_persist = true

[[kv_namespaces]]
binding = "CORRUPTIONS"
preview_id = "3a3347ec91f3422eaa16f64e02f51869"
id = "caeaaa50e7eb486dac05188d607f8393"

# [secrets]
# ALCHEMY_URL
# MORALIS_URL
# MORALIS_APP_ID